version: '3'

services:
  mongodb:
    container_name: vogi-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  rebbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:var/lib/rabbitmq
    hostname: rabbitmq
  
volumes:
  mongodbdata:
  rabbitmqdata: 
